# Generated by Django 3.0.5 on 2020-04-13 22:01

from django.db import migrations, models
import nuHome_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('nuHome_app', '0002_auto_20200413_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugee_profile',
            name='verification_document',
            field=models.FileField(null=True, upload_to=nuHome_app.models.user_directory_path),
        ),
    ]
